# Generated by Django 3.0.2 on 2020-04-23 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=400, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('test_creados', models.IntegerField(default=0)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero_preguntas', models.IntegerField(default=0)),
                ('fecha_test', models.DateField()),
                ('duracion', models.IntegerField()),
                ('maxima_puntuacion', models.IntegerField()),
                ('descripcion', models.CharField(max_length=4000, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testtestapp.Categoria')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testtestapp.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=4, max_digits=6)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testtestapp.Test')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testtestapp.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=4000)),
                ('puntos', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testtestapp.Test')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testtestapp.Tipo_Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=4000)),
                ('puntos', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testtestapp.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_integrantes', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('contrasena', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=4000, null=True)),
                ('tests', models.ManyToManyField(to='testtestapp.Test')),
                ('usuarios', models.ManyToManyField(to='testtestapp.Usuario')),
            ],
        ),
    ]
