# Generated by Django 3.0.4 on 2020-04-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testtestapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='categoria',
            field=models.ForeignKey(default='Geografía', on_delete=django.db.models.deletion.CASCADE, to='testtestapp.Categoria'),
            preserve_default=False,
        ),
    ]
