# Generated by Django 3.0.2 on 2020-04-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testtestapp', '0002_test_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
